request: 
  OWASP_CSRFTOKEN: "50EZ-G70X-HNY2-RR4C-P7TK-NX1Q-PCQH-9TG3"
  orderid: "14106635"
  zoneid: "14106635"
  domainname: "foxflower.tech"
  type: "A"
  rrid: "156515201"
  name: "foxflower.tech"
  clazz: "IN"
  IPvalue: "94.147.71.291"
  ttl: "7200"
  duration: "seconds"
  submitform: "Modify+Record"
JSESSIONID: "D25CDE506645EB6929A82AE72970395D"
modify_url: "https://14106635.dns.bll.myorderbox.com/dnsbox/servlet/ModRecordServlet"
login_url: ""